config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'sink#index'
  get "profile" => "users#show", :as => 'profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sink_controller.rb
class SinkController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #users_controller.rb
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sink_helper.rb
module SinkHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_login.html.erb
<%= form_for(:user, :url => session_path(:user)) do |f| %>
  <%= f.text_field :email %>
  <%= f.password_field :password %>
  <%= f.check_box :remember_me %>
  <%= f.label :remember_me %>
  <%= f.submit 'Sign in' %>
  <%= link_to "Forgot your password?", new_password_path(:user) %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="db dt-l w-100 border-box pa3 ph5-l">
    <a class="db dtc-l v-mid mid-gray link dim w-100 w-25-l tc tl-l mb2 mb0-l" href="#" title="Home">
        <%= image_tag('logo.png', :class => 'dib w2 h2 br-100')%>
    </a>
    <div class="db dtc-l v-mid w-100 w-75-l tc tr-l">
        <%= link_to "Home", root_url, :class => 'link dim dark-gray f6 f5-l dib mr3 mr4-l' %>
        <%= link_to "Blog", root_url, :class => 'link dim dark-gray f6 f5-l dib mr3 mr4-l' %>
        <%= link_to "Contact Us", root_url, :class => 'link dim dark-gray f6 f5-l dib mr3 mr4-l' %>
        <% if user_signed_in? %>
          <li><%= link_to "Profile", profile_path %></li>
          <%= link_to 'Logout', destroy_user_session_path, :class => 'link dim dark-gray f6 f5-l dib', :method => :delete %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, :class => 'link dim dark-gray f6 f5-l dib'  %>
        <% end %>
    </div>
</nav>

app/views/layouts/_notifications.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_profile.html.erb
<a class="db dtc-l v-mid mid-gray link dim w-100 w-25-l tc tl-l mb2 mb0-l" href="#" title="Home">
    <%= image_tag('profile.png', :class => 'dib w2 h2 br-100')%>
</a>

app/views/layouts/_signup.html.erb
<%= form_for(:user, :url => session_path(:user)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reuse</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.5.1/css/tachyons.min.css"/>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/sink/_grid.html.erb
<div class="container">
    <div class="row">
        <div class="c1">
            1
        </div>
        <div class="c2">
            2
        </div>
        <div class="c3">
            3
        </div>
        <div class="c6">
            6
        </div>
    </div>
    <div class="row">
        <div class="c5">
            5
        </div>
        <div class="c7">
            7
        </div>
    </div>
    <div class="row">
        <div class="c8">
            8
        </div>
        <div class="c4">
            4
        </div>
    </div>
    <div class="row">
        <div class="c1">
            1
        </div>
        <div class="c10">
            10
        </div>
        <div class="c1">
            1
        </div>
    </div>
    <div class="row">
        <div class="c1">
            1
        </div>
        <div class="c11">
            11
        </div>
    </div>
    <div class="row">
        <div class="c12">
            12
        </div>
    </div>
</div>

app/views/sink/index.html.erb
<h1>The Sink</h1>
<h2>The Nav Bar</h2>
<%= render "layouts/navbar" %>
<h2>The Grid</h2>
<%= render "sink/grid" %>
<h2>The Sign Up</h2>
<%= render "layouts/signup" %>
<h2>The Login</h2>
<%= render "layouts/login" %>
<h2>The Profile</h2>
<%= render "layouts/profile" %>

app/views/users/show.html.erb
<%= @user.email %>